[supabase]
url = "https://oxbrezracnmazucnnqox.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94YnJlenJhY25tYXp1Y25ucW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjUxMTgsImV4cCI6MjA2OTM0MTExOH0.nqBK2ZxntesLY9qYClpoFPVnXOW10KrzF-UI_DkjbKo"

DATABASE_URL = "postgresql://postgres:Waytosuccess@2025@db.cbmlsqqncdpfejmpnstb.supabase.co:5432/postgres"
